language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: DKNLhYdLgLzJ//4QOljY8SM+++C0dS3KzuNUJ0GE/BJoHU5Z1rghmhyiuSq8EWVrPd4yj33E5ajZE0vlTsY9+Jv68+0vbMY/+ItvU0CSIwL+XiMFdANK5Nf+Ka0ZMk4mX70Mkw0r4Ftzl4Zn/89JZ51214c1JSGNJL+IbUd3E7eHYzQtBk9XGsg6jOA+qP0K8nU0jwvrEaiTUZHq5kQqK9lveKS3cVkCtnPg3iEoGtbF8HL20FJT0I6eqqo2XD8Oh1n/jC7g5ZRve6+rBRIlK5hwcnf3Wj0/oCaFASYJEhfZyIAAm8i8PWS4SeKBn2a0w+XvzAhy3I/mKobzmKlXDX1nNrsfq3WYCl7OEby1zAugn74IutTB5HwuHF/9rFnvxjycG/TTtg9IbL/t8w06egsV1q+aI/PdANdIh5YO7S8tqDA6oFtFS9HQCpCo8OYkKF5Clv6I/91Mz6BRQlJ1w2maHcaEt2/G32Mgse15T0UVoz8hnYF0iSq2UCsFxRRuE+DpnDEZMCC+m0ZbQSflZNud/5pkz+CQnUUMh/enjouDKYzwWUL7nu3z30Lu1Huqaj/cP57dP3xJqXJfR4ZzvnRr7fMfK2XVLCK8V2+CZJNUO3fF5PNvUBiTs7wsZTVI01p2+u/EBbeCExVb8L/lWBKCQy2rwlBpx8mCrw/qoKk=
  app: quiet-caverns-77861
