language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: EsVGN9lB7/18CiZe7/7u8S3pt1I4gFbQHc+ruG2tj4OTCZ2lyvcom8FAQ1E0pLU3Gb6Ru1A7gtHtl7ZpypsNPgTaTKlCaJk3J05+UNfcvUIC1KTRDg2zC4vzuCSh3f+5IaYizXQ/4IxVQANuRJCiSncT//og5DWi7hpHtuV0tVHkWX83k9J0KdVZYGBPUwftWhci6ycRZYb9tgq6Aro7MNMcAkVzAT+vz7i3YHE9nT44IKh2SS2oG5UMlt6EKc50kH4FIECVxt7VXeBKU3WHLRko6SzvH3KQk8syKpQ1WSexd/meuJgJvTt0GhGV4NbnUfbn7ijSc3SfaMD4u+7yWJSRl0/xlAN6kakN15WuvXWQFtrD85Uki3WcRhfXFUY5L0HgxqQHXtRjRU14zO3mRgN5LrCIl77Elubo2EMMqq4rIXvgDQItlUCFcTMRrE9036VdXvVZRKDYUmC2udSaIG3bejlKPUvjszVWYLQKDmspZI5xKTO9zfRak7bqaW1w5+KlbheejggCezUZWuiW+LWsFyI3jShtR+r36cpaYM7poB59I14ZF//SpX+WfUxAAJed6ZxAS3JXYUQL7BOyezSa+uoagblsUkf0B5Hcq4ZQ3n0YQVUo/NXWfsqY3WsRy0FyCQSjQDh477rJosahDlKABaj1cHXXzyGmovCNIgY=
  app: quiet-caverns-77861
