language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: ptl6o3Y/zcQsssBxJv6M10oh2qgWZOaRzZVtu55CKP/7WRjELRzzOKjGBz0qRSBs2LpMPF69OyILotOmR6F8MUx8Z7isLq4N5fWvkJ8jwdxTQT+UAeAeDsM+XvydFw+oZRuQMNPDgTE572GJhgDuaq91U+ZNLNP6HnbwLSrxeOOf9rOFBp+ESLYIM63zoPGZlL6u8Srr8HKecy7gjVXvlukRX4pPAcdLqKQifC+bSWbVkZBKWA73Ogc0UJNWSTTl9tHaSheZqxDusEsKk8We22Z2PGTvVlTaZTJtkmBZMOvToQHwcWwnHxYOllan/WGL8/zBsWrc34XGPlCc8u+i+qjqh2IUYWapW0iIOAP6ab6EpI+CwWlXWpCBni83pOrSYulbsUSMmme11FBmQffN/ZsaJU8m6c9pAgvhyih3JNfGT6tItli54IfmVZIOAyrgEWCmgVBdqUN0Oa1TvUoicv4Y+DL4ntgipsYNGhBoXG/CQfzv7WVJB3jnMMQMZqv6Jd9yKRFc2ToQSiZL5GTdESqNVd6s8JrU0Io5aVCP3mRJE6Hqh1t5HWCfkyJlxg8NXVUs3nFTFuBp2vFE9t/qJsrjHpZ1kb5UQGgIU8sASwZ20JXUI3JQNWqNWf4ewR78aCFkYcY5I4evH9HnWVfL2I1YA2gvSsQrUAGJ8bjZqwo=
  app: quiet-caverns-77861
